package com.company.gum.util.passworEncoder;

import org.mindrot.jbcrypt.BCrypt;
import org.pac4j.core.util.CommonHelper;

public class JBCryptPasswordEncoder implements PasswordEncoder {

    private String salt;

    public JBCryptPasswordEncoder(final String salt) {
        this.salt = salt;
    }

    /**
     * Use the default salt generated by {@link BCrypt#gensalt()}.
     */
    public JBCryptPasswordEncoder() {
        this.salt = BCrypt.gensalt();
    }

    @Override
    public static String encode(final String password) {
        CommonHelper.assertNotBlank("salt", salt);

        return BCrypt.hashpw(password, salt);
    }

    @Override
    public boolean matches(final String plainPassword, final String encodedPassword) {
        CommonHelper.assertNotBlank("salt", salt);

        return BCrypt.checkpw(plainPassword, encodedPassword);
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }
}